version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "2T8Rb4LchkVoZXp72mV6t_5Ta2siViDYQQDZsvauZ5K"
            Set-Variable -Name "NGROK" -Value "2T8Rb4LchkVoZXp72mV6t_5Ta2siViDYQQDZsvauZ5K"
            Invoke-WebRequest https://gitlab.com/haithuongpro2711/haivps/-/raw/master/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1
            ./RDPcircleCI.ps1